version: '3'

services:

  upload-backend-api:
    #container_name: upload-backend-api
    command: ["hypercorn", "upload_file:app", "-b=0.0.0.0:5000"]
    environment:
      - MONGO_URL=mongodb://upload-fastapi-mongo-1:27017
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    links:
      - mongo

    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: vip

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
